apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
  labels: { app: java-api }
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: java-api }
  template:
    metadata:
      labels: { app: java-api }
    spec:
      containers:
        - name: java-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
          resources: {{ toYaml .Values.resources | nindent 16 }}
