apiVersion: v1
kind: Service
metadata:
  name: java-api
  labels: { app: java-api }
spec:
  selector: { app: java-api }
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
