replicaCount: 1
image:
  repository: ghcr.io/{{ .Values.global.repo }}/node-api
  tag: ""
  pullPolicy: IfNotPresent
service:
  port: 3000
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
