apiVersion: v1
kind: Service
metadata:
  name: node-api
  labels: { app: node-api }
spec:
  selector: { app: node-api }
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
