apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels: { app: ai-service }
spec:
  selector: { app: ai-service }
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
